base = int(input("Digite um numero para ver a sua tabuada: "))
print("_"*12)
print("{} x  {:2} = {:3}".format(base, 1, base*1))
print("{} x  {:2} = {:3}".format(base, 2, base*2))
print("{} x  {:2} = {:3}".format(base, 3, base*3))
print("{} x  {:2} = {:3}".format(base, 4, base*4))
print("{} x  {:2} = {:3}".format(base, 5, base*5))
print("{} x  {:2} = {:3}".format(base, 6, base*6))
print("{} x  {:2} = {:3}".format(base, 7, base*7))
print("{} x  {:2} = {:3}".format(base, 8, base*8))
print("{} x  {:2} = {:3}".format(base, 9, base*9))
print("{} x  {:2} = {:3}".format(base, 10, base*10))
print("_"*12)
