n1 = int(input("Digite o primeiro número: "))
n2 = int(input("Digite o segundo número: "))
n3 = int(input("Digite o terceiro número: "))
print ("O maior número é: {} ".format(max(n1, n2, n3)))
print ("O menor número é: {} ".format(min(n1, n2, n3)))